from binaryTree import BinaryTree

tr = BinaryTree([5,9,7,4,6,1,2,8])
print(tr)
print('find 2', tr.search(2))
print('find 22', tr.search(22))
print('testing deletion')
print('delete 2')
tr.delete(2)
print(tr)
tr = BinaryTree([5,9,7,4,6,1,2,8])
print('delete 1')
tr.delete(1)
print(tr)
tr = BinaryTree([5,9,7,4,6,1,2,8])
print('delete 7')
tr.delete(7)
print(tr)
tr = BinaryTree([5,9,7,4,6,1,2,8])
print('delete 5')
tr.delete(5)
print(tr)
tr = BinaryTree([5,9,7,4,6,1,2,8])

tr = BinaryTree([5,9,7,4,6,1,2,8])
# in order predecessor test
tNode = tr.search(5)
pNode = tr.subtreePredecessor(tNode)
print('in order predecessor of 5:', pNode.data if pNode else None)

tNode = tr.search(4)
pNode = tr.subtreePredecessor(tNode)
print('in order predecessor o 4:', pNode.data if pNode else None)

tNode = tr.search(7)
pNode = tr.subtreePredecessor(tNode)
print('in order predecessor of 7:', pNode.data if pNode else None)

tNode = tr.search(9)
pNode = tr.subtreePredecessor(tNode)
print('in order predecessor of 9:', pNode.data if pNode else None)

tNode = tr.search(2)
pNode = tr.subtreePredecessor(tNode)
print('in order predecessor of 2:', pNode.data if pNode else None)

tNode = tr.search(1)
pNode = tr.subtreePredecessor(tNode)
print('in order predecessor of 1:', pNode.data if pNode else None)
print('--------------------------------------')
tNode = tr.search(5)
pNode = tr.subtreeSuccessor(tNode)
print('in order successor of 5:', pNode.data if pNode else None)
tNode = tr.search(4)
pNode = tr.subtreeSuccessor(tNode)
print('in order successor of 4:', pNode.data if pNode else None)
tNode = tr.search(7)
pNode = tr.subtreeSuccessor(tNode)
print('in order successor of 7:', pNode.data if pNode else None)
tNode = tr.search(9)
pNode = tr.subtreeSuccessor(tNode)
print('in order successor of 9:', pNode.data if pNode else None)
tNode = tr.search(2)
pNode = tr.subtreeSuccessor(tNode)
print('in order successor of 2:', pNode.data if pNode else None)
tNode = tr.search(1)
pNode = tr.subtreeSuccessor(tNode)
print('in order successor of 1:', pNode.data if pNode else None)
